###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=Yorobo2027
            - MYSQL_DATABASE=iabd_mtn
            - MYSQL_USER=azk
            - MYSQL_PASSWORD=esatic
        ports:
            - '55002:3306'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '55001:80'
        restart: always
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '55000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
